
[aliases]
b = ["bookmark"]
n = ["new"]

[revsets]
log = "present(@) | ancestors(immutable_heads().., 10) | trunk()"

[ui]
paginate = "never"
default-command = ["log", "--reversed"]
diff-tool = "difft"

[merge-tools.difft]
program = "difft"
diff-args = ["--color=always", "$left", "$right"]
